# Números no python

<br>
<br>
1. python puro
2. numpy: operações numéricas, matrizes (scipy: operações mais avançadas) 
3. pandas: operações com dataframes (outro notebook)
<br>
<br>

### aritmética e operações

In [1]:
3 * 9 / (2 + 7)

3.0

In [2]:
x = 20
y = 10
x / y

2.0

In [3]:
x * y

200

In [4]:
x ** y # potenciação

10240000000000

In [5]:
2 ** 3

8

### duas estratégias mais avançadas

In [8]:
print(2 + 9)
3 + 9

11


12

In [5]:
# atribuição múltipla
a, b = 56, 78
a + b

134

In [6]:
c, d, e = [3, 4, 5], [34, 567, 0], [90, 49, 22]
print(c, d, e)
print(c, d)

[3, 4, 5] [34, 567, 0] [90, 49, 22]


In [10]:
x = [2, 3]
a, b = x
b

3

In [11]:
# =+
a = 10
a -= 2  # equivalent to a = a + 2
a

8

Em python, tudo é objeto e tem metadata (atributos) e funcionalidades (métodos).

### Comparações booleanas

| Operation     | Description                       || Operation     | Description                          |
|---------------|-----------------------------------||---------------|--------------------------------------|
| ``a == b``    | ``a`` equal to ``b``              || ``a != b``    | ``a`` not equal to ``b``             |
| ``a < b``     | ``a`` less than ``b``             || ``a > b``     | ``a`` greater than ``b``             |
| ``a <= b``    | ``a`` less than or equal to ``b`` || ``a >= b``    | ``a`` greater than or equal to ``b`` |

In [17]:
# 25 is odd
25 % 2 == 1

1

In [20]:
# check if a is between 15 and 30
a = 55
15 < a < 30

False

In [21]:
x = 4
(x < 6) and (x > 2)

True

In [22]:
(x > 10) or (x % 2 == 0)

True

In [23]:
not (x < 6)

False

In [30]:
L = [1, 2, 3]

In [31]:
len(L)

3

In [33]:
L.append([3, 4, 5,])
L

[1, 2, 3, 4, [3, 4, 5]]

In [34]:
L + [20, 23]

[1, 2, 3, 4, [3, 4, 5], 20, 23]

In [18]:
L = [4, 76, 908]
L.sort()
L

[4, 76, 908]

In [35]:
# mas não é um vetor do R
L * 2

[1, 2, 3, 4, [3, 4, 5], 1, 2, 3, 4, [3, 4, 5]]

In [20]:
L = [189, 'e aí, véi?', 3.4, [2, 3, 4] ]
L

[189, 'e aí, véi?', 3.4, [2, 3, 4]]

In [36]:
# índice começa em 0
L[0]

1

In [37]:
# start inclusive, end point non-inclusive
L[0:2]

[1, 2]

In [23]:
L[:2]

[189, 'e aí, véi?']

In [38]:
L[-3:] # últimos três

[3, 4, [3, 4, 5]]

In [39]:
# também serve para definir elementos
L[0] = 1000000
L

[1000000, 2, 3, 4, [3, 4, 5]]

In [40]:
# dictionaries
numeros = {'um':1, 'dois':2}
numeros

{'dois': 2, 'um': 1}

In [27]:
# itens são acessado com a chave
numeros['dois']

2

In [42]:
# podem ser adicionados itens, não há ordenação
numeros['noventa'] = 90
numeros['saraiva'] =4545
numeros

{'dois': 2, 'noventa': 90, 'saraiva': 4545, 'um': 1}

### Controle do fluxo
conditional statements (including "if", "elif", and "else") and loop statements (including "for" and "while")

In [ ]:
# estrutura condicional (o computador fazendo escolhas)
# note o uso de :, espaço e elif(else if)

x = int(input('O Alex quer que você digite um número'))

if x == 0:
    print(x, "é zero")
elif x > 0:
    print(x, "é positivo")
elif x < 0:
    print(x, "é negativão")
else:
    print(x, "is unlike anything I've ever seen...")

In [30]:
# loop

for CHUCHU in [2, 3, 5, 7]:
    print(CHUCHU) # print all on same line

2
3
5
7


In [1]:
for i in range(10):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [7]:
list(range(5, 109, 20))

[5, 25, 45, 65, 85, 105]

In [33]:
list(range(0, 20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [34]:
# while

i = 0
while i < 10:
    print(i, end=' ')
    i += 1

0 1 2 3 4 5 6 7 8 9 

In [8]:
# criando funções

def soma(a, b):
    return a + b

In [36]:
soma(8, 9)

17

In [37]:
def media(a, b, c):
    return (a + b + c)/3
media(10, 5, 7)

7.333333333333333

### Numpy

computação numérica (arrays, vetores, matrizes etc.) 

In [10]:
from numpy import *

In [11]:
# ndarray é criado com listas
dados = array([2.1, 3.3, 4.6])
dados

array([ 2.1,  3.3,  4.6])

In [13]:
dados * 87 / dados

array([ 87.,  87.,  87.])

In [14]:
# criando sequência
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arange(0, 2010, 10)

array([   0,   10,   20,   30,   40,   50,   60,   70,   80,   90,  100,
        110,  120,  130,  140,  150,  160,  170,  180,  190,  200,  210,
        220,  230,  240,  250,  260,  270,  280,  290,  300,  310,  320,
        330,  340,  350,  360,  370,  380,  390,  400,  410,  420,  430,
        440,  450,  460,  470,  480,  490,  500,  510,  520,  530,  540,
        550,  560,  570,  580,  590,  600,  610,  620,  630,  640,  650,
        660,  670,  680,  690,  700,  710,  720,  730,  740,  750,  760,
        770,  780,  790,  800,  810,  820,  830,  840,  850,  860,  870,
        880,  890,  900,  910,  920,  930,  940,  950,  960,  970,  980,
        990, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090,
       1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190, 1200,
       1210, 1220, 1230, 1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310,
       1320, 1330, 1340, 1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420,
       1430, 1440, 1450, 1460, 1470, 1480, 1490, 15

In [17]:
# listas de tamanho igual viram array multidimensional. 
# PS: note os colchetes duplos: lista de listas
dados2 = [[2.1, 3.3, 4.6], [2.1, 3.3, 4.6]]
dados2 = array(dados2)
dados2

array([[ 2.1,  3.3,  4.6],
       [ 2.1,  3.3,  4.6]])

In [18]:
dados2 + 4

array([[ 6.1,  7.3,  8.6],
       [ 6.1,  7.3,  8.6]])

In [19]:
# array vazio
# PS: note os parêntesis duplos (é um tuple, uma lista imutável)) 
zeros((10, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [20]:
# matriz identidade
identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
# identificando o tipo de número
dados = arange(10)
dados.dtype

dtype('int64')

In [22]:
# convertendo
dados = dados.astype(float64)
dados.dtype

dtype('float64')

In [23]:
# operações
dados = array([[1, 2, 3], [4, 5, 6]])
dados

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
dados * dados

array([[ 1,  4,  9],
       [16, 25, 36]])

In [25]:
dados - dados

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
1/dados

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [27]:
dados ** dados

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [28]:
dados

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# subselecionar
dados[1, 1]

5

In [66]:
# modificar
dados[0:1, ] = 2
dados

array([[2, 2, 2],
       [4, 5, 6]])

In [53]:
# criando novo array
dados = arange(10)
dados

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dados[5:8]

In [ ]:
dados[5:8] = 12
dados

### atenção
#### o índice começa é em 0, não 1

0,0  0,1  0,2  
1,0  1,1  1,2  
2,0  2,2  2,2  

In [54]:
# array de três dimensões
# note os três colchotes

arr3d = array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr3d * 10

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

In [57]:
arr3d[1] = 12
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12, 12, 12],
        [12, 12, 12]]])

In [61]:
# strings em arrays
nomes = array(['zé', 'maria', 'maria', 'zé', 'carol', 'cleusinha'])
nomes

array(['zé', 'maria', 'maria', 'zé', 'carol', 'cleusinha'], 
      dtype='<U9')

In [62]:
unique(nomes)

array(['carol', 'cleusinha', 'maria', 'zé'], 
      dtype='<U9')

In [63]:
nomes == 'zé'

array([ True, False, False,  True, False, False], dtype=bool)

In [66]:
# criar array com dados aleatórios 
dados = random.randn(7, 4)
dados

array([[-0.15036012, -1.67876328, -2.1166254 , -0.44177146],
       [-0.47915871, -0.15178123, -0.3772205 ,  0.38024011],
       [ 0.08829738,  0.34950555,  3.17743578,  0.9001806 ],
       [ 1.65110157,  1.52940673,  1.8255721 , -0.07419078],
       [-1.92925072,  0.16746926,  2.40505883, -0.69890221],
       [-0.26279398,  0.87654318,  0.51640598,  0.98376482],
       [-0.23442668, -0.14783345, -1.42804901, -1.70513141]])

In [68]:
empty(9)


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [69]:
# reorganizar array
arange(50).reshape(10, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [70]:
dados = arange(10).reshape(2, 5)
sqrt(dados)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ]])

In [71]:
exp(dados)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01,   5.45981500e+01],
       [  1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
          2.98095799e+03,   8.10308393e+03]])

In [72]:
dados.mean()

4.5

In [73]:
dados.std()

2.8722813232690143

In [74]:
dados.sum()

45

In [75]:
dados.max()

9

In [76]:
dados.mean(axis=1)

array([ 2.,  7.])

In [77]:
# ordenar
dados.sort()
dados

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
# encontrar quantis
dados = random.randn(1000)
dados.sort()
dados[int(0.05*len(dados))] # quantil 5% 

-1.734156131055347

In [32]:
# multiplicando matrizes
matriz1 = array([[2, 3, 3], [3, -4, 4]])
matriz2 = array([[3, -3], [-1, 1], [0, 0]])
dot(matriz1, matriz2)

array([[  3,  -3],
       [ 13, -13]])

In [33]:
matriz1 * matriz2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

#### Para mais álgebra linear:

numpy.linalg (álgebra linear): determinante, inversa, traço, diagonal, autovalor, solve (solução de sistemas de equações) etc  

In [81]:
# geração de números aleatórios: numpy.random (normal, uniforme, binomial etc.)
amostra = random.normal(size=(4, 4))
amostra

array([[ 0.59500559, -2.05495569,  3.21681332, -1.70554245],
       [ 0.4748294 , -1.95123295,  0.32216321,  0.56117689],
       [ 0.19380868, -0.01778011,  0.90324349,  0.94307086],
       [ 0.01340243, -2.27869562, -1.17775382, -0.34833231]])

#### Para mais distribuições estatísticas: 
scipy.stats

In [34]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
